jfangonilo/adopt_dont_shop_part_two

app/controllers/shelter_reviews_controller.rb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/shelters/show_spec.rb
Able to delete individual shelter reviews from shelter show page.
closes #16 
Figuring out correct routes.
n/a
n/a
=> Delete shelter review functionality

app/controllers/pets_controller.rb, app/controllers/shelter_reviews_controller.rb, app/controllers/shelters_controller.rb, app/views/pets/new.html.erb, app/views/shelter_reviews/edit.html.erb, app/views/shelter_reviews/new.html.erb, app/views/shelters/edit.html.erb, spec/features/pets/edit_spec.rb, spec/features/pets/index_spec.rb, spec/features/pets/show_spec.rb, spec/features/shelters/index_spec.rb, spec/features/shelters/show_spec.rb
Refactor controllers to reduce number of DB calls
Knowing to even to do this in the first place
=> DB Call Refactors

spec/factories/pets.rb, spec/factories/shelter_reviews.rb, spec/factories/shelters.rb
Refactor specific pieces of faker in factorybot so producing unique data.
Just deciding on which pieces to sequence and which to leave.
n/a
n/a, discussed before PR which to leave as is.
=> Refactor factorybot

app/controllers/shelter_reviews_controller.rb, app/views/layouts/application.html.erb, app/views/shelter_reviews/edit.html.erb, config/routes.rb, spec/features/shelter_reviews/edit_spec.rb
closes #14 
Adds sad path testing for empty fields in update
Finding out that we need to pass instance variables through update action as well if we're rendering edit in update.
Make sure you pass through the needed variables when you're rendering a view
=> Edit Sad Path

app/controllers/shelters_controller.rb, app/views/shelters/index.html.erb, spec/features/shelters/index_spec.rb
Changes shelter index to show shelters alphabetically by default
=> Shelter Index Alpha Sort

app/controllers/application_controller.rb, app/controllers/favorites_controller.rb
=> Changes that did't make it in last PR

app/controllers/favorites_controller.rb, app/views/favorites/index.html.erb, config/routes.rb, spec/features/favorites/index_spec.rb, spec/features/pets/edit_spec.rb
Favorites now has an index page with name and image of each pet.
closes #4 
Refactored to take logic out of view.
n/a
n/a
I tried.
=> Favorite index

app/controllers/favorites_controller.rb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/application_spec.rb, spec/features/favorites/index_spec.rb, spec/features/favorites/show_spec.rb
closes #6 
closes #11 
Add topnav link to Favorites Page
Add flash message if no pets in favorites
Add favorite pet show page
Needed to instantiate a new hash for favorite session if one doesn't already exist
=> Favorite Link to Index

app/controllers/favorites_controller.rb, app/views/favorites/index.html.erb, config/routes.rb, spec/features/favorites/index_spec.rb
closes #12 
Add functionality to remove all favorites
Using session.delete instead of reset_session
https://stackoverflow.com/questions/2405635/how-to-empty-destroy-a-session-in-rails
=> 15 remove all favorites

app/controllers/favorites_controller.rb, app/models/favorites.rb, app/views/pets/index.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/favorites/destroy_spec.rb, spec/models/favorites_spec.rb
-Can delete individual pet from favorites from the pet's show page
-Flash message tells that pet was deleted from favorites
-Nav bar pet total correctly reflects total favorites post deletion
closes #8 
Incorporating model methods, but good practice!
n/a
Need to get together for PR merge to decide on how want to handle two separate destroy methods.
=> Delete individual pet from favorites

app/controllers/favorites_controller.rb
Lost an end in our last PR
I don't like making merge conflict fixes in GH
=> Add missing end lost in PR

app/controllers/applications_controller.rb, app/views/applications/show.html.erb, config/routes.rb, db/seeds.rb, spec/factories/applications.rb, spec/factories/pets.rb, spec/factories/shelter_reviews.rb, spec/features/applications/show_spec.rb
closes #18 
Add application show page
N/A - straightforward
=> 19 application show

app/controllers/applications_controller.rb, app/views/applications/index.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/factories/applications.rb, spec/features/applications/index_spec.rb
closes #19 
Add index page for applications
Please merge application show page first, and check to make sure last two tests in index spec pass (they were dependent on application show)
=> 20 application index

app/controllers/applications_controller.rb, db/seeds.rb, spec/features/applications/index_spec.rb
closes #21 
Shows flash message for pets without applications
Flash vs Flash.now
=> User Story 21

app/views/favorites/index.html.erb, spec/features/favorites/index_spec.rb
Add section to see all pets with applications from favorites index page
closes #17 
Hitting the right test...
-Already knew, keep forgetting, can reference specific test to run: .rb:58
=> 18 applications

app/controllers/pets_controller.rb, spec/features/pets/show_spec.rb
closes #32 
Deleting a favorited pet removes it from favorites
=> User Story 32

app/views/pets/_form.html.erb, app/views/pets/edit.html.erb, app/views/pets/new.html.erb, app/views/shelter_reviews/_form.html.erb, app/views/shelter_reviews/edit.html.erb, app/views/shelter_reviews/new.html.erb, app/views/shelters/_form.html.erb, app/views/shelters/edit.html.erb, app/views/shelters/new.html.erb
Refactored to implement partials for creating and editing forms for shelters, pets, and shelter reviews.
closes #
Pretty straightforward.
=> Partials refactor

app/controllers/applications_controller.rb, app/controllers/pet_applications_controller.rb, app/controllers/pets_controller.rb, app/models/favorites.rb, app/models/pet.rb, app/models/pet_application.rb, app/views/applications/show.html.erb, app/views/pets/show.html.erb, config/routes.rb, db/migrate/20191210004336_add_status_to_pet_applications.rb, db/migrate/20191210042005_remove_nil_values.rb, db/schema.rb, spec/features/applications/show_spec.rb, spec/features/pets/index_spec.rb, spec/features/pets/show_spec.rb, spec/models/favorites_spec.rb, spec/models/pet_application_spec.rb, spec/models/pet_spec.rb
closes #22 
Allows for approval of pet applications and shows applicant name
Had trouble making query on a pet object
Meg was awesome!
=> 22 pet applications

spec/features/applications/show_spec.rb
closes #24 
Added test to make allow for more than one pet to be approved. No new code
=> User Story 23

app/controllers/pet_applications_controller.rb, app/models/pet.rb, app/views/applications/show.html.erb, spec/features/applications/show_spec.rb
closes #29 
Adds functionality for revoking applications
Please note opportunities to refactor
=> User Story 25

app/models/pet.rb, app/views/applications/show.html.erb, spec/features/applications/show_spec.rb, spec/models/pet_spec.rb
Refactor one approved, so shows different message based on whether viewed application is approved or not.
closes #
=> Refactor one approved

app/models/pet.rb, spec/models/pet_spec.rb
Refactor so pets with applications doesn't show repeated names
closes #
=> Refactor pets with applications

app/controllers/pets_controller.rb, app/models/pet.rb, spec/features/applications/delete_spec.rb, spec/models/pet_spec.rb
closes #30 
Display flash message for deleting pets w/ pending applications
=> User Story 31

app/controllers/pets_controller.rb, app/controllers/shelters_controller.rb, spec/features/pets/edit_spec.rb, spec/features/pets/new_spec.rb, spec/features/shelters/edit_spec.rb, spec/features/shelters/new_spec.rb
closes #26 
closes #35 
Add flash messages for incomplete fields in pet/shelter update/create
https://stackoverflow.com/questions/8252783/passing-error-messages-through-flash
=> User Story 29 & 33 - Add/Update Flash Messages

app/views/applications/index.html.erb, app/views/applications/new.html.erb, app/views/applications/show.html.erb, app/views/favorites/index.html.erb, app/views/pets/_form.html.erb, app/views/pets/edit.html.erb, app/views/pets/index.html.erb, app/views/pets/new.html.erb, app/views/pets/show.html.erb, app/views/shelter_pets/index.html.erb, app/views/shelter_reviews/_form.html.erb, app/views/shelter_reviews/edit.html.erb, app/views/shelter_reviews/new.html.erb, app/views/shelters/_form.html.erb, app/views/shelters/edit.html.erb, app/views/shelters/index.html.erb, app/views/shelters/new.html.erb, app/views/shelters/show.html.erb
=> User Experience

spec/features/applications/show_spec.rb, spec/features/pets/index_spec.rb, spec/features/shelter_reviews/new_spec.rb, spec/features/shelters/show_spec.rb
Go through tests so passing with new messages/page title, and sections on show pages.
closes #
=> Refactor tests

app/models/pet.rb, app/views/favorites/index.html.erb, spec/features/favorites/index_spec.rb, spec/models/pet_spec.rb
closes #36 
Adds list of pets with pending applications to favorites page
=> User Story 37 - Approved Applications

app/models/pet.rb, app/models/pet_application.rb, app/models/shelter.rb, app/views/shelters/show.html.erb, spec/features/shelters/show_spec.rb, spec/models/pet_application_spec.rb, spec/models/pet_spec.rb, spec/models/shelter_spec.rb
-Adds how many pets at shelter, average shelter review rating, and number of applications for each shelter on show page.
-Refactored pet and pet applications validations for activerecord false/nil issues
closes #28 
Active Record queries across multiple joins! More that needed string interpolation in the query.
=> Shelter statistics
